#!/bin/bash
#

#google-chrome --headless=new --screenshot="docs/img/github-profile.png" --hide-scrollbars --window-size=1620,1080 "https://github.com/robinmordasiewicz"

#google-chrome --headless=new --screenshot="docs/img/github-fork-repo.png" --hide-scrollbars --window-size=1620,1080 "https://github.com/robinmordasiewicz/devops-toolkit/fork"

#sgpt "Respond with the markdown syntax that will be used in a README.md file. mkdocs metadata frontmatter with the title, author, date in format %Y-%M-%D, and \"comments: \"true\". Wrap the frontmatter section enclosed in three dashes. In the front matter include comments: true. Do not include a please or thank you. Do not include a welcome message. Do not include a goodbye message. Do not include a signature. Do not include a greeting. Do not include a closing. Do not include a salutation. Do not include a closing salutation. Do not include a closing greeting. Do not include a closing signature. Do not include a closing goodbye message. Do not include a closing welcome message. Create the article in the style of technical instructional blog. Do not include a summary section. Keep the content precise and to the point. Use bullet points and tables to organize the content. Use the markdown syntax for the bullet points and tables. Keep the content concise and to the point. Do not include any fluff. Do not include any filler. Do not include any unnecessary words. Do not include any unnecessary sentences. Do not include any unnecessary paragraphs. Do not include any unnecessary sections. Do not include any unnecessary chapters. Do not include any unnecessary pages. Keep the content length to one page. Make sure that the markdown generated is syntactically correct according to Github README.md style. Make the title of the article three words. Do not include the markdown fence line at the top of the document. The content of the blag article will be about what is the purpose of a folder named .git in a github repository."

#sgpt --code "write a markdown page to let people know how to sign up for github copilot" > docs/github-copilot.md
#sgpt --code "writes markdown page to describe a demo where a user forks a github repository robinmordasiewicz/devops-toolkit branch named feature1 is created for a user to make their commits. The style guide conventional commits is used as a reference in creating commits. The use will use opencommit command from a zsh shell. In the markdown guide, create steps as an unordered list. Also in the markdown file show the bash commands to execute each step. Give each section a short title. As a pre-requisite instruction, have users install opencommit from github and use the cli command oco to stage, commit and push changes. Highlight a step that demonstrates following style guides for commits such as the conventional commits style guide. The user will use the opencommit command from a zsh shell. In the markdown guide, create steps as an unordered list. Also in the markdown file show the bash commands to execute each step. Give each section a short title." > docs/demo.md

#sgpt --code "write a markdown page informing readers that subsequent steps in the instructions require opencommit to be installed install with the instructions found on this website https://github.com/di-sukharev/opencommit. Title the markdown page as OpenCommit" >docs/opencommit.md
#sgpt --code "write a markdown page instructing users step by step how to install opencommit from github. Keep the titles of each section three words." >docs/opencommit-install.md
#sgpt --code "write a markdown page instructing users step by step how to configure opencommit to use conventional commits style. Keep the titles of each section three words." >docs/opencommit-conventional.md

#sgpt --code "write a markdown page instructing users step by step how to install copilot as a vim plugin. Include a Usage section in the markdown documentation to show how see if copilot is active in vim. Keep the page title to three words." >docs/github-copilot-install.md

#sgpt --code "write a markdown page instructing users step by step with short titles and sections, how to sign up for a DockerHub account" >docs/account-docker.md

#sgpt "write a markdown file that lets people know that this is the beginning of a guide that requires users to have login accounts in github with copilot, azure, docker, and openai. For each of the accounts in the list, include the login page as a link in markdown. Make the title of the markdown document 'Accounts'. Do not use please and thank you in the documentation" >docs/accounts.md

# sgpt "write a one page markdown file with step by step instructions on how to configure OIDC in Azure to authenticate a github repository using the web interfaces and include links to screenshots of the web interface that show where to click. Include the equivalent az cli commands and make sure that the fenced code blocks are set to bash. Include a summary which shows how to test and validate from the cli that the authentication works." > docs/azure-oidc.md
