location            = "canadacentral"
resource_group      = "my-resource-group"
owner_email         = "root@example.com"
vnet_address_prefix = "10.0.0.0/16"
external_name       = "external"
external_prefix     = "10.0.1.0/24"
internal_name       = "internal"
internal_prefix     = "10.0.2.0/24"
