---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fortiweb-ingress-controller
  namespace: cluster-config
spec:
  interval: 30m
  url: https://fortinet.github.io/fortiweb-ingress/
  # url: https://fortiweb-fortiadc.github.io/fortiweb-ingress/
