---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa
  namespace: dvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: dvwa
          image: ghcr.io/digininja/dvwa:latest
          env:
            - name: DB_SERVER
              value: mariadb
          resources:
            requests:
              cpu: 1m
              memory: 200Mi
            limits:
                cpu: 1000m
                memory: 512Mi
          ports:
            - containerPort: 80
              name: http
      initContainers:
        - name: init-myservice
          image: alpine/k8s:1.30.2
          command: ['sh', '-c', 'IPADDRESS=$(kubectl -n dvwa get svc dvwa -o json | jq -r ".spec.clusterIP"); JSONDATA=$(kubectl -n fos get configmaps fos-vip-template -o json | jq "{data,apiVersion,kind}"); YAMLDATA=$(echo $JSONDATA | yq -P | sed -e s/VAR_CLUSTER_IP/${IPADDRESS}/g); echo -e "---\nmetadata:\n  labels:\n    app: fos\n    category: config\n  name: VAR_APP_NAME\n  namespace: fos\n$YAMLDATA" > manifest.yaml; kubectl apply -f manifest.yaml']
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa
  namespace: dvwa
  labels:
    app: dvwa
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dvwa
  type: ClusterIP
