---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: dvwa-read-svc
    namespace: dvwa
subjects:
    - kind: ServiceAccount
      name: default
      apiGroup: ""
      namespace: dvwa
roleRef:
    kind: ClusterRole
    name: svc-reader
    apiGroup: ""
