---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flannel
  namespace: cluster-config
spec:
  targetNamespace: kube-flannel
  releaseName: flannel
  chart:
    spec:
      chart: flannel
      sourceRef:
        kind: HelmRepository
        name: flannel-repo
        namespace: cluster-config
  interval: 10m0s
  install:
    remediation:
      retries: 3
