---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fos-deployment
  namespace: fos
  labels:
    app: fos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fos
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/fos: unconfined
      labels:
        app: fos
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: fos
          image: ghcr.io/robinmordasiewicz/fos:latest
          ports:
            - containerPort: 80
              name: fos
            - name: isakmp
              containerPort: 500
              protocol: UDP
            - name: ipsec-nat-t
              containerPort: 4500
              protocol: UDP
          volumeMounts:
            - mountPath: /data
              name: data-volume
          env:
            - name: fos-license
              valueFrom:
                configMapKeyRef:
                  name: license
                  key: license
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add: ["NET_ADMIN", "SYS_ADMIN", "NET_RAW"]
          resources:
            requests:
              cpu: 4m
              memory: 2Gi
            limits:
              cpu: 8000m
              memory: 4096Mi
      volumes:
        - name: data-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: fos
  namespace: fos
spec:
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: fos
  type: ClusterIP
