---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: fos-clusterrole
rules:
    - apiGroups: [""]
      resources: ["secrets", "configmaps", "deployments"]
      verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fos-clusterrole-binding
  namespace: fos
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
    namespace: fos
roleRef:
  kind: ClusterRole
  name: fos-clusterrole
  apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: config-map-manager
rules:
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: config-map-manager
    namespace: fos
subjects:
    - kind: ServiceAccount
      name: default
      apiGroup: ""
      namespace: dvwa
    - kind: ServiceAccount
      name: ollama
      apiGroup: ""
      namespace: ollama
roleRef:
    kind: ClusterRole
    name: config-map-manager
    apiGroup: ""
