---
- name: Update /etc/hosts file on localhost
  hosts: localhost
  become: yes  # Escalate privileges to modify /etc/hosts
  tasks:
    - name: Ensure temporary hosts file
      copy:
        content: ""
        dest: /etc/hosts.temp
        force: yes
        owner: root
        group: root
        mode: 0644
    - name: Add entry to /etc/hosts
      lineinfile:
        path: /etc/hosts.temp
        line: "216.254.141.2 www.bankexample.com"
        state: present
        create: yes
    - name: Move temporary hosts to actual hosts
      command: mv /etc/hosts.temp /etc/hosts
