---
name: openai-pr-description

on: # yamllint disable-line rule:truthy
  pull_request:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write
  actions: write

jobs:
  init:
    name: init
    runs-on: ubuntu-latest
    outputs:
      action: ${{ steps.init.outputs.action }}
    steps:
      - id: init
        name: "init"
        shell: bash
        run: |
          if [[ -n "${{ secrets.OPENAI_API_KEY }}" ]]
          then
              echo 'action=true' >> "${GITHUB_OUTPUT}"
          else
            echo 'action=false' >> "${GITHUB_OUTPUT}"
          fi
  openai-pr-description:
    needs: [init]
    if: needs.init.outputs.action == 'true' && github.head_ref != 'release-please--branches--main'
    name: openai-pr-description
    runs-on: ubuntu-22.04

    steps:
      - uses: platisd/openai-pr-description@ae9234941eb14118caf3a0171bf15dcd4a4ee880
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
