---
name: "pages-build-integration"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "requirements.txt"
      - "README.md"
      - ".github/workflows/pages-build-integration.yml"

concurrency:
  group: "pages-build-integration"
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  pages-build-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          fetch-depth: 0

      #  - name: Configure GitHub Pages
      #  uses: actions/configure-pages@f156874f8191504dae5b037505266ed5dda6c382

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docs
        env:
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force
